package service

import (
	"StreamRoom/errz"
	"StreamRoom/internal/queue"
	"StreamRoom/storage"
	"StreamRoom/util"
	"context"
	"errors"
	"fmt"
	"time"
)

// VideoService owns the upload/ingest side of the transcode pipeline:
// issuing presigned upload URLs, verifying uploads actually landed, and
// enqueueing TranscodeJob work for the Go worker fleet. It never touches
// video bytes itself -- that's the worker's job (internal/worker).
type VideoService struct {
	r2           *storage.R2MediaService
	producer     queue.Producer
	sourceBucket string
}

func NewVideoService(r2 *storage.R2MediaService, producer queue.Producer, sourceBucket string) *VideoService {
	return &VideoService{r2: r2, producer: producer, sourceBucket: sourceBucket}
}

// GenerateUploadUrl issues a short-lived presigned PUT URL that the client
// uploads its raw source video to directly -- the API server is never in
// the request path for the (potentially large) file bytes themselves.
func (s *VideoService) GenerateUploadUrl(ctx context.Context, roomID string) (uploadURL string, objectKey string, err error) {
	objectKey = fmt.Sprintf("uploads/%s/%s.mp4", roomID, util.NewID("src"))
	uploadURL, err = s.r2.GenerateUploadURL(ctx, "video/mp4", objectKey)
	if err != nil {
		return "", "", err
	}
	return uploadURL, objectKey, nil
}

// ConfirmUpload is the trust boundary for client-confirmed uploads: it
// verifies the object actually exists in the bucket via HeadObject rather
// than taking the client's word for it, then enqueues a transcode job
// under jobID (generated by the caller -- see RoomService.ConfirmVideoUpload
// for why the caller, not this method, owns JobID generation).
func (s *VideoService) ConfirmUpload(ctx context.Context, roomID, objectKey, jobID string) (*queue.TranscodeJob, error) {
	info, err := s.r2.HeadObject(ctx, objectKey)
	if err != nil {
		return nil, errz.NewBadRequest(fmt.Sprintf("upload not found in storage yet: %v", err))
	}
	if info.SizeBytes <= 0 {
		return nil, errz.NewBadRequest("uploaded object is empty")
	}
	return s.enqueue(ctx, roomID, objectKey, jobID, info, "client-confirm")
}

// IngestStorageEvent handles a verified bucket "object created" event
// pointing at a newly-written source object. bucket is validated against
// the configured source bucket -- an event for some other bucket is
// rejected rather than silently processed against the wrong one, since
// downloadSource always reads from this service's configured bucket
// regardless of what the event claims.
func (s *VideoService) IngestStorageEvent(ctx context.Context, roomID, bucket, objectKey, jobID string, sizeBytes int64, etag string) (*queue.TranscodeJob, error) {
	if bucket != "" && bucket != s.sourceBucket {
		return nil, errz.NewBadRequest(fmt.Sprintf("storage event bucket %q does not match configured source bucket %q", bucket, s.sourceBucket))
	}
	info := &storage.ObjectInfo{SizeBytes: sizeBytes, ETag: etag}
	return s.enqueue(ctx, roomID, objectKey, jobID, info, "webhook")
}

func (s *VideoService) enqueue(ctx context.Context, roomID, objectKey, jobID string, info *storage.ObjectInfo, source string) (*queue.TranscodeJob, error) {
	job := queue.TranscodeJob{
		JobID:       jobID,
		RoomID:      roomID,
		Bucket:      s.sourceBucket,
		ObjectKey:   objectKey,
		ContentType: info.ContentType,
		SizeBytes:   info.SizeBytes,
		ETag:        info.ETag,
		Source:      source,
		EnqueuedAt:  time.Now(),
	}

	if err := s.producer.Enqueue(ctx, &job); err != nil {
		if errors.Is(err, queue.ErrDuplicateJob) {
			// Already in flight or done (duplicate bucket-event delivery,
			// or a retried confirm call) -- not an error from the caller's
			// point of view. Enqueue has already corrected job.JobID to
			// whichever job actually owns this object version.
			return &job, nil
		}
		return nil, fmt.Errorf("enqueue transcode job: %w", err)
	}
	return &job, nil
}
